//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kredi_Kartı_Takip.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddExpense
    {
        public int id { get; set; }
        public Nullable<int> cardId { get; set; }
        public string companyName { get; set; }
        public string explanationCompany { get; set; }
        public string productCategory { get; set; }
        public Nullable<int> numberOfInstallments { get; set; }
        public string installmentAmount { get; set; }
        public string aggregateAmount { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public Nullable<int> mailOrder { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
    }
}
